default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") { 'postgresql' } %>
  encoding: <%= ENV.fetch("DATABASE_ENCODING") { 'unicode' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rtemp_db

test:
  <<: *default
  database: rtemp_db_test

production:
  <<: *default
  database: rtemp_db
